import { quickTravelDestinations, type QuickTravelId } from '../game/data/quickTravel';

/** Native buttons retain Tab/Enter/Space and touch behavior; this is navigation,
 * not an ARIA application menu. The decorative glove never changes the name.
 */
export class QuickTravelMenu {
  private readonly buttons: HTMLButtonElement[] = [];
  private readonly cleanups: (() => void)[] = [];

  public constructor(
    private readonly container: HTMLElement,
    onTravel: (id: QuickTravelId) => void,
    onFocus: () => void,
  ) {
    container.className = 'quick-travel';
    container.setAttribute('aria-label', 'Quick travel');
    for (const destination of quickTravelDestinations) {
      const button = document.createElement('button');
      button.type = 'button';
      button.textContent = destination.label;
      button.dataset.destination = destination.id;
      button.disabled = true;
      const select = () => this.select(button);
      const focus = () => { onFocus(); select(); };
      const click = () => { select(); onTravel(destination.id); };
      button.addEventListener('pointerenter', select);
      button.addEventListener('focus', focus);
      button.addEventListener('click', click);
      this.cleanups.push(() => {
        button.removeEventListener('pointerenter', select);
        button.removeEventListener('focus', focus);
        button.removeEventListener('click', click);
      });
      this.buttons.push(button);
      container.append(button);
    }
    this.select(this.buttons[0]!);
    // Stop global gameplay keys while using the menu, without suppressing the
    // native button activation generated by Enter and Space.
    const keydown = (event: KeyboardEvent) => {
      event.stopPropagation();
      const index = this.buttons.indexOf(document.activeElement as HTMLButtonElement);
      const next = event.key === 'ArrowDown' ? (index + 1) % this.buttons.length
        : event.key === 'ArrowUp' ? (index + this.buttons.length - 1) % this.buttons.length
        : event.key === 'Home' ? 0 : event.key === 'End' ? this.buttons.length - 1 : undefined;
      if (next !== undefined) { event.preventDefault(); this.buttons[next]!.focus(); }
    };
    container.addEventListener('keydown', keydown);
    this.cleanups.push(() => container.removeEventListener('keydown', keydown));
  }

  public setEnabled(enabled: boolean): void {
    this.buttons.forEach(button => { button.disabled = !enabled; });
  }

  public destroy(): void {
    this.cleanups.forEach(cleanup => cleanup());
    this.container.replaceChildren();
  }

  private select(selected: HTMLButtonElement): void {
    this.buttons.forEach(button => { button.dataset.highlighted = String(button === selected); });
  }
}
