import { quickTravelDestinations, type QuickTravelId } from '../game/data/quickTravel';
import type { RoomDefinition } from '../game/data/types';

/** Native buttons retain Tab/Enter/Space and touch behavior; this is navigation,
 * not an ARIA application menu. The decorative glove never changes the name.
 */
export class QuickTravelMenu {
  private readonly buttons: HTMLButtonElement[] = [];
  private readonly cleanups: (() => void)[] = [];
  private currentRoom?: RoomDefinition['id'];

  public constructor(
    private readonly container: HTMLElement,
    onTravel: (id: QuickTravelId) => void,
    onFocus: () => void,
  ) {
    container.className = 'quick-travel';
    container.setAttribute('aria-label', 'Quick travel');
    for (const destination of quickTravelDestinations) {
      const button = document.createElement('button');
      button.type = 'button';
      button.textContent = destination.label;
      button.dataset.destination = destination.id;
      button.dataset.highlighted = 'false';
      button.disabled = true;
      const focus = () => onFocus();
      const click = () => onTravel(destination.id);
      button.addEventListener('focus', focus);
      button.addEventListener('click', click);
      this.cleanups.push(() => {
        button.removeEventListener('focus', focus);
        button.removeEventListener('click', click);
      });
      this.buttons.push(button);
      container.append(button);
    }
    // Stop global gameplay keys while using the menu, without suppressing the
    // native button activation generated by Enter and Space.
    const keydown = (event: KeyboardEvent) => {
      event.stopPropagation();
      const index = this.buttons.indexOf(document.activeElement as HTMLButtonElement);
      const next = event.key === 'ArrowDown' ? (index + 1) % this.buttons.length
        : event.key === 'ArrowUp' ? (index + this.buttons.length - 1) % this.buttons.length
        : event.key === 'Home' ? 0 : event.key === 'End' ? this.buttons.length - 1 : undefined;
      if (next !== undefined) { event.preventDefault(); this.buttons[next]!.focus(); }
    };
    container.addEventListener('keydown', keydown);
    this.cleanups.push(() => container.removeEventListener('keydown', keydown));
  }

  public setEnabled(enabled: boolean): void {
    this.buttons.forEach(button => { button.disabled = !enabled; });
  }

  public destroy(): void {
    this.cleanups.forEach(cleanup => cleanup());
    this.container.replaceChildren();
  }

  /** Only confirmed scene location moves the glove, never hover/focus/travel intent. */
  public setCurrentRoom(roomId: RoomDefinition['id']): void {
    if (roomId === this.currentRoom) return;
    this.currentRoom = roomId;
    this.buttons.forEach((button, index) => {
      const current = quickTravelDestinations[index]!.roomId === roomId;
      button.dataset.highlighted = String(current);
      if (current) button.setAttribute('aria-current', 'location');
      else button.removeAttribute('aria-current');
    });
  }
}
